### ISSUE TITLE
JsonResourceTest fails irregularly  

### ISSUE THREAD

**Issue by asereda** [alex-shpak/rx-jersey#2] opened 2017-04-01 02:04 UTC
After running `gradle clean test`  a couple of times, the follwing tests fail sporadically: 

> net.winterly.rx.jersey.JsonResourceTest > shouldReadJsonEntities FAILED
> net.winterly.rx.jersey.JsonResourceTest > shouldWriteJsonEntities FAILED
  
### Error message
```
org.glassfish.jersey.message.internal.MessageBodyProviderNotFoundException: 
MessageBodyReader not found for media type=text/html;charset=ISO-8859-1, 
type=class net.winterly.rx.jersey.JsonResourceTest$Message, genericType=class 
```

I believe something is wrong with imported libraries (providers).

**Comment by alex-shpak** [comment] 2017-04-01 09:44
Hi. thanks for reporting!
I was able to reproduce it, happens always for me if I run only that test.

I will investigate it. Looks like `Content-Type` is incorrect in response from server, but it only appears in test.

**Comment by alex-shpak** [comment] 2017-04-01 10:05
Looks like an issue with Grizzly container, should be fixed now.

**Comment by asereda** [comment] 2017-04-01 16:48
I debugged a little myself. And it looked like `RxBodyWriter` was not called (registered) inside  `jersey.message.internal.MessageBodyFactory` when test failed.

The following helped
```java
@Produces(MediaType.APPLICATION_JSON) // force media type
public class RxBodyWriter {
...
```
Not sure if it is related to container or not.

**Comment by asereda** [comment] 2017-04-01 16:52
Unfortunately with jetty container it still fails for me.

**Comment by alex-shpak** [comment] 2017-04-02 10:27
I wanted to keep `MessageBodyWriter` without `@Produces` to support not only json output.
Since it's hard to reproduce on my computer can you please try with annotation `@org.glassfish.hk2.api.Rank(1)` on `RxBodyWriter` class?

**Comment by alex-shpak** [comment] 2017-04-02 11:41
https://github.com/alex-shpak/rx-jersey/commit/c50a8773d077a4eef8cb59c5534d936a674e06e0 This should fix it.
Travis build is passing now: https://travis-ci.org/alex-shpak/rx-jersey/builds/217754112

**Comment by asereda** [comment] 2017-04-03 19:28
Yes `@Priority` annotation seem to fix the issue

**Closed** 2017-04-04 08:37 UTC
Labels: bug
